name: master_dbt_models
version: '2.0'
config-version: 2
require-dbt-version: ">=0.13.0"
# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: vidyard_redshift

# These configurations specify where dbt should look for different types of files.  The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
 - "target"
 - "dbt_modules"

# You can define configurations for models in the `source-paths` directory here.
# Using these configurations, you can enable or disable models, change how they
# are materialized, and more!

# These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  bind: false
  master_dbt_models:
      staging:
        +materialized: view
      marts:
        +materialized: table
      kubes:
        +materialized: table

