name: master_dbt_models
version: '1.0'

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: vidyard_redshift

# These configurations specify where dbt should look for different types of files.  The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
 - "target"
 - "dbt_modules"

# You can define configurations for models in the `source-paths` directory here.
# Using these configurations, you can enable or disable models, change how they
# are materialized, and more!

# These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  materialized: ephemeral
  enabled: true

  vidyard_unified_record:
    materialized: ephemeral
    database: dev

  vars:
    internal_domains:
      - vidyard.com
      - viewedit.com

# run hooks
on-run-start:
  - CREATE TABLE IF NOT EXISTS census.enrichment_results_raw (
      service VARCHAR,
      enrichment_key VARCHAR,
      enrichment_value VARCHAR,
      updated_at TIMESTAMPTZ,
      data VARCHAR
    );