with
  raw_country_data as (
    select
      lower(billingcountry) as country
    from
      {{ ref('tier2_salesforce_account') }}
    union
    select
      lower(mailingCountry) as country
    from
      {{ ref('tier2_salesforce_contact') }}
  )
select
  *
  , case when country in (
    'australia'
    ,'thailand'
    ,'south korea'
    ,'singapore'
    ,'hong kong'
    ,'china (hong kong s.a.r.)'
    ,'vietnam'
    ,'jp'
    ,'bangladesh'
    ,'republic of korea'
    ,'cambodia'
    ,'kazakhstan'
    ,'au'
    ,'aus'
    ,'ch'
    ,'china'
    ,'chinese taipei'
    ,'hk'
    ,'hong kong (sar)'
    ,'in'
    ,'india'
    ,'indonesia'
    ,'japan'
    ,'korea'
    ,'korea rep of'
    ,'korea south'
    ,'korea, democratic peoples republic of'
    ,'korea, republic of'
    ,'new zealand'
    ,'newzealand'
    ,'nz'
    ,'papua new guinea'
    ,'ph'
    ,'philippines'
    ,'phillipines'
    ,'bengal'
    ,'laos'
    ,'macau'
    ,'malaysia'
    ,'maldives'
    ,'marshall islands'
    ,'mobercial inc'
    ,'mongolia'
    ,'myanmar'
    ,'myanmar (burma)'
    ,'nepal'
    ,'new caledonia'
    ,'northern mariana islands'
    ,'pitcairn'
    ,'reunion'
    ,'réunion'
    ,'reunion island'
    ,'sri lanka'
    ,'sri lanka.'
    ,'taiwan'
    ,'taiwan, province of china'
    ,'taiwan, republic of china'
    ,'united states minor outlying islands'
    ,'viet nam'
    ,'cl'
    ,'cn'
    ,'sg'
    ,'sk'
    ,'american samoa'
    ,'bhutan'
    ,'brunei'
    ,'christmas island'
    ,'democratic republic of timor-leste'
    ,'east timor'
    ,'federated states of micronesia'
    ,'fiji'
    ,'french polynesia'
    ,'guam'
    ,'heard island and mcdonald islands'
    ,'kiribati'
    ,'kyrgyzstan'
    ,'macao'
    ,'nauru'
    ,'niue'
    ,'norfolk island'
    ,'north korea'
    ,'palau'
    ,'samoa'
    ,'solomon islands'
    ,'tajikistan'
    ,'tuvalu'
    ,'u.s. minor outlying islands'
    ,'vanuatu'
    ,'wallis and futuna'
    ,'apac'


  ) then 'apac'
  when country in (
    'united kingdom'
    ,'finland'
    ,'belgium'
    ,'switzerland'
    ,'serbia'
    ,'italy'
    ,'armenia'
    ,'ireland (republic)'
    ,'europe'
    ,'nigeria'
    ,'greece'
    ,'luxembourg'
    ,'fr'
    ,'romainia'
    ,'lithuania'
    ,'belarus'
    ,'amsterdam'
    ,'liechtenstein'
    ,'slovakia'
    ,'albania'
    ,'republic of ireland'
    ,'angola'
    ,'denmark'
    ,'great britain'
    ,'greater munich metropolitan area'
    ,'faroe islands'
    ,'moldova'
    ,'north holland'
    ,'monaco'
    ,'virgin islands, british'
    ,'senegal'
    ,'rwanda'
    ,'the slovak republic'
    ,'africa'
    ,'south holland'
    ,'algeria'
    ,'andorra'
    ,'austria'
    ,'azerbaijan'
    ,'be'
    ,'belguim'
    ,'berlin'
    ,'bosnia and herzegovina'
    ,'britain'
    ,'british indian ocean territory'
    ,'british virgin islands'
    ,'c“te d''ivoire'
    ,'cameroon'
    ,'congo (democratic rep)'
    ,'côte d''ivoire'
    ,'croatia'
    ,'cyprus'
    ,'cz'
    ,'czech republic'
    ,'czechia'
    ,'de'
    ,'deutschland'
    ,'dk'
    ,'eg'
    ,'egypt'
    ,'eng'
    ,'england'
    ,'es'
    ,'españa'
    ,'estonia'
    ,'ethiopia'
    ,'european union'
    ,'fi'
    ,'france'
    ,'france-fr'
    ,'fulham, united kingdom'
    ,'gabon'
    ,'gambia'
    ,'gb'
    ,'ge'
    ,'germany'
    ,'ghana'
    ,'gibraltar'
    ,'haiti'
    ,'hungary'
    ,'iceland'
    ,'ireland'
    ,'ireland(republic)'
    ,'it'
    ,'ivory coast'
    ,'kenya'
    ,'latvia'
    ,'macedonia (fyrom)'
    ,'macedonia, the former yugoslav republic of'
    ,'netherladnds'
    ,'netherlands'
    ,'niger'
    ,'nl'
    ,'north macedonia'
    ,'northern ireland'
    ,'norway'
    ,'poland'
    ,'portugal'
    ,'republic of macedonia'
    ,'romania'
    ,'russia'
    ,'russian federation'
    ,'san marino'
    ,'scotland'
    ,'slovenia'
    ,'slovenská republika'
    ,'somalia'
    ,'south africa'
    ,'spain'
    ,'sweden'
    ,'switerzland'
    ,'swizerland'
    ,'tanzania'
    ,'tanzania, united republic of'
    ,'the netherlands'
    ,'the united kingdom'
    ,'tonga'
    ,'turkey'
    ,'uganda'
    ,'uk'
    ,'ukraine'
    ,'united kingdm'
    ,'united kingdom of great britain and northern ireland'
    ,'united kingdon'
    ,'vatican city'
    ,'wales'
    ,'zambia'
    ,'zimbabwe'
    ,'benelux'
    ,'benin'
    ,'botswana'
    ,'bouvet island'
    ,'bruchem'
    ,'bulgaria'
    ,'burundi'
    ,'georgia'
    ,'guernsey'
    ,'isle of man'
    ,'kosovo'
    ,'libya'
    ,'malawi'
    ,'mali'
    ,'malta'
    ,'mauritius'
    ,'meyrin'
    ,'montenegro'
    ,'morocco'
    ,'mozambique'
    ,'namibia'
    ,'republic of lithuania'
    ,'tunisia'
    ,'li'
    ,'no'
    ,'pt'
    ,'se'
    ,'åland'
    ,'burkina faso'
    ,'cabo verde'
    ,'cape verde'
    ,'central african republic'
    ,'chad'
    ,'comoros'
    ,'congo'
    ,'congo republic'
    ,'djibouti'
    ,'dr congo'
    ,'equatorial guinea'
    ,'eritrea'
    ,'eswatini'
    ,'french southern territories'
    ,'guinea'
    ,'guinea-bissau'
    ,'lesotho'
    ,'liberia'
    ,'macedonia'
    ,'madagascar'
    ,'mauritania'
    ,'mayotte'
    ,'principality of monaco'
    ,'republic of moldova'
    ,'republic of the congo'
    ,'são tomé and príncipe'
    ,'seychelles'
    ,'sierra leone'
    ,'slovak republic'
    ,'south sudan'
    ,'sudan'
    ,'swaziland'
    ,'togo'
    ,'western sahara'
    ,'emea'

  ) then 'emea'
  when country in (
    'mexico'
    ,'brazil'
    ,'puerto rico'
    ,'bolivia'
    ,'jamaica'
    ,'venezuela'
    ,'ecuador'
    ,'the bahamas'
    ,'barbados'
    ,'curaçao'
    ,'brasil'
    ,'honduras'
    ,'trinidad & tobago'
    ,'cura‡ao'
    ,'anguilla'
    ,'ar'
    ,'argentina'
    ,'aruba'
    ,'bahamas'
    ,'belize'
    ,'bermuda'
    ,'bolivia, plurinational state of'
    ,'br'
    ,'chile'
    ,'colombia'
    ,'columbia'
    ,'costa rica'
    ,'curacao'
    ,'dominican republic'
    ,'el salvador'
    ,'guadeloupe'
    ,'guatemala'
    ,'méxico'
    ,'mexico, df'
    ,'mx'
    ,'nicaragua'
    ,'panama'
    ,'paraguay'
    ,'peru'
    ,'plurinational state of bolivia'
    ,'saint kitts and nevis'
    ,'saint vincent and the grenadines'
    ,'trinidad and tobago'
    ,'uruguay'
    ,'venezuela, bolivarian republic of'
    ,'antigua and barbuda'
    ,'bvi'
    ,'cayman islands'
    ,'cocos (keeling) islands'
    ,'cook'
    ,'guyana'
    ,'st. lucia'
    ,'u.s. virgin islands'
    ,'ve'
    ,'bonaire, sint eustatius, and saba'
    ,'cook islands'
    ,'cuba'
    ,'dominica'
    ,'falkland islands'
    ,'french guiana'
    ,'grenada'
    ,'martinique'
    ,'montserrat'
    ,'saint barthélemy'
    ,'saint lucia'
    ,'saint martin'
    ,'saint-barthélemy'
    ,'sint maarten'
    ,'st kitts and nevis'
    ,'st vincent and grenadines'
    ,'suriname'
    ,'turks and caicos islands'
    ,'latam'

  ) then 'latam'
  when country in (
    'united arab emirates'
    ,'pakistan'
    ,'royal jordanian'
    ,'oman'
    ,'iraq'
    ,'afghanistan'
    ,'bahrain'
    ,'dubai'
    ,'iq'
    ,'iran'
    ,'iran, islamic republic of'
    ,'israel'
    ,'isreal'
    ,'jordan'
    ,'kuwait'
    ,'lebanon'
    ,'palestine'
    ,'saudi arabia'
    ,'turkmenistan'
    ,'ua'
    ,'uae'
    ,'uzbekistan'
    ,'qatar'
    ,'yemen'
    ,'hashemite kingdom of jordan'
    ,'jordan'
    ,'syria'

  ) then 'middle east'
  when country in (
    'united states'
    ,'[logo-valcartier-fr]'
    ,'corvallis, oregon 97331'
    ,'wisconsin'
    ,'markham, canada'
    ,'pacifica, united states'
    ,'america'
    ,'united'
    ,'washington'
    ,'cananda'
    ,'1801'
    ,'2110'
    ,'2113'
    ,'2155'
    ,'2451'
    ,'6897'
    ,'20036'
    ,'27613'
    ,'27703'
    ,'30033'
    ,'30326'
    ,'33913'
    ,'53226'
    ,'59047'
    ,'60606'
    ,'66219'
    ,'75201'
    ,'78626'
    ,'78757'
    ,'84043'
    ,'93108'
    ,'94043'
    ,'94103'
    ,'94105'
    ,'94107'
    ,'94110'
    ,'94123'
    ,'94132'
    ,'94401'
    ,'94538'
    ,'94587'
    ,'94612'
    ,'95008'
    ,'95054'
    ,'95060'
    ,'95115'
    ,'95125'
    ,'98004'
    ,'98012'
    ,'98109'
    ,'98134'
    ,'ca'
    ,'california'
    ,'can'
    ,'canada'
    ,'jersey'
    ,'k0k'
    ,'m9w 4y8'
    ,'new york'
    ,'oakland, united states'
    ,'ontario'
    ,'pa'
    ,'springfield, united states'
    ,'the united states'
    ,'toronto, canada'
    ,'tx'
    ,'u.s.'
    ,'united sates'
    ,'united staes'
    ,'united statees'
    ,'united states of america'
    ,'united states-us'
    ,'us'
    ,'us,'
    ,'usa'
    ,'uunited states'
    ,'v6z 1n9'
    ,'windermere, fl'
    ,'na'
    ,'il'
    ,'ks'
    ,'ky'
    ,'greenland'
    ,'saint pierre and miquelon'
    ,'na - west'
    ,'na - east'
    ,'lawrenceville, nj'

  ) then 'na'
  when country in (
    null
    , ''
    ,'antarctica'
    ,'none'
    ,'--'
    ,'[unknown]'
    ,'3513ew'
    ,'62215-0128'
    ,'63128-2172'
    ,'810-0042'
    ,'94043-2212'
    ,'ae'
    ,'country'
    ,'country not listed'
    ,'other'
    ,'quandl'
    ,'unknown'
    ,'xx'
    ,'bh'
    ,'by'
    ,'co'
    ,'cr'
    ,'ec'
    ,'ee'
    ,'gt'
    ,'hn'
    ,'id'
    ,'ie'
    ,'om'
    ,'oo'
    ,'pd'
    ,'pe29 6xx'
    ,'rg1 1ax'
    ,'rg6 6gp'
    ,'sp3 4ln'
    ,'tn'
    ,'za'
    ,'zz'

  ) then 'unknown'
  else 'unknown unclassified' end as region
from
  raw_country_data
group by
  1
